apiVersion: v2
appVersion: 1.18.0
description: A Helm chart for installing Percona XtraDB Cluster Databases using the PXC Operator.
name: pxc-db
home: https://www.percona.com/doc/kubernetes-operator-for-pxc/kubernetes.html
version: 1.18.0
maintainers:
  - name: eleo007
    email: eleonora.zinchenko@percona.com
  - name: nmarukovich
    email: natalia.marukovich@percona.com
  - name: jvpasinatto
    email: julio.pasinatto@percona.com
icon: https://artifacthub.io/image/0b8875cd-6661-4269-9cf6-0fd92d59017b@1x
