apiVersion: v2
appVersion: 1.14.0
description: A Helm chart for installing Percona XtraDB Cluster Databases using the PXC Operator.
name: pxc-db
home: https://www.percona.com/doc/kubernetes-operator-for-pxc/kubernetes.html
version: 1.14.4
maintainers:
  - name: tplavcic
    email: tomislav.plavcic@percona.com
  - name: spron-in
    email: sergey.pronin@percona.com
  - name: nmarukovich
    email: natalia.marukovich@percona.com
icon: https://artifacthub.io/image/0b8875cd-6661-4269-9cf6-0fd92d59017b@1x
