apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster1-init-sql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pmm.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  init.sql: |
    \c pmm-managed
    CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

