apiVersion: v2
appVersion: "0.3.0"
description: A Helm chart for installing Percona Server Databases using the PS Operator.
name: ps-db
home: https://www.percona.com/doc/kubernetes-operator-for-mysql/ps
version: 0.3.1
maintainers:
  - name: tplavcic
    email: tomislav.plavcic@percona.com
  - name: cap1984
    email: ivan.pylypenko@percona.com
  - name: nmarukovich
    email: natalia.marukovich@percona.com
