apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    helm.sh/chart-name: everest-crds
    helm.sh/chart-version: 0.0.0
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.3
  name: backupstorages.everest.percona.com
spec:
  group: everest.percona.com
  names:
    kind: BackupStorage
    listKind: BackupStorageList
    plural: backupstorages
    singular: backupstorage
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: BackupStorage is the Schema for the backupstorages API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object.

              Servers should convert recognized schemas to the latest internal value,
              and

              may reject unrecognized values.

              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents.

              Servers may infer this from the endpoint the client submits requests
              to.

              Cannot be updated.

              In CamelCase.

              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: BackupStorageSpec defines the desired state of BackupStorage.
            properties:
              allowedNamespaces:
                description: 'AllowedNamespaces is the list of namespaces where the
                  operator will copy secrets provided in the CredentialsSecretsName.


                  Deprecated: BackupStorages are now used only in the namespaces where
                  they are created.'
                items:
                  type: string
                type: array
              bucket:
                description: Bucket is a name of bucket.
                type: string
              credentialsSecretName:
                description: CredentialsSecretName is the name of the secret with
                  credentials.
                type: string
              description:
                description: Description stores description of a backup storage.
                type: string
              endpointURL:
                description: EndpointURL is an endpoint URL of backup storage.
                type: string
              forcePathStyle:
                default: false
                description: 'ForcePathStyle is set to use path-style URLs.

                  If unspecified, the default value is false.'
                type: boolean
              region:
                description: Region is a region where the bucket is located.
                type: string
              type:
                description: Type is a type of backup storage.
                enum:
                - s3
                - azure
                type: string
              verifyTLS:
                default: true
                description: 'VerifyTLS is set to ensure TLS/SSL verification.

                  If unspecified, the default value is true.'
                type: boolean
            required:
            - bucket
            - credentialsSecretName
            - type
            type: object
          status:
            description: BackupStorageStatus defines the observed state of BackupStorage.
            properties:
              usedNamespaces:
                additionalProperties:
                  type: boolean
                description: 'Deprecated: BackupStorages are now used only in the
                  namespaces where they are created.'
                type: object
            required:
            - usedNamespaces
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
