apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    everest.percona.com/crd: "true"
    everest.percona.com/version: "0.0.0"
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.3
  name: monitoringconfigs.everest.percona.com
spec:
  group: everest.percona.com
  names:
    kind: MonitoringConfig
    listKind: MonitoringConfigList
    plural: monitoringconfigs
    singular: monitoringconfig
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Monitoring instance type
      jsonPath: .spec.type
      name: Type
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MonitoringConfig is the Schema for the monitoringconfigs API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: MonitoringConfigSpec defines the desired state of MonitoringConfig.
            properties:
              allowedNamespaces:
                description: AllowedNamespaces is the list of namespaces where the
                  operator will copy secrets provided in the CredentialsSecretsName.
                items:
                  type: string
                type: array
              credentialsSecretName:
                description: CredentialsSecretName is the name of the secret with
                  credentials.
                type: string
              pmm:
                description: PMM is configuration for the PMM monitoring type.
                properties:
                  image:
                    description: Image is a Docker image name to use for deploying
                      PMM client. Defaults to using the latest version.
                    type: string
                  url:
                    description: URL is url to the monitoring instance.
                    type: string
                required:
                - image
                - url
                type: object
              type:
                description: Type is type of monitoring.
                enum:
                - pmm
                type: string
              verifyTLS:
                default: true
                description: |-
                  VerifyTLS is set to ensure TLS/SSL verification.
                  If unspecified, the default value is true.
                type: boolean
            required:
            - credentialsSecretName
            - type
            type: object
          status:
            description: MonitoringConfigStatus defines the observed state of MonitoringConfig.
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}