apiVersion: v1
appVersion: "1.9.0"
description: A Helm chart for Deploying the Percona Kubernetes Operator for Percona Server for MongoDB
name: psmdb-operator
home: https://www.percona.com/doc/kubernetes-operator-for-psmongodb/kubernetes.html
version: 1.9.0
maintainers:
  - name: cap1984
    email: ivan.pylypenko@percona.com
  - name: tplavcic
    email: tomislav.plavcic@percona.com
  - name: paulczar
    email: username.taken@gmail.com
