apiVersion: v2
appVersion: "1.13.0"
description: A Helm chart for deploying the Percona Operator for MongoDB
name: psmdb-operator
home: https://docs.percona.com/percona-operator-for-mongodb/
version: 1.13.2
maintainers:
  - name: cap1984
    email: ivan.pylypenko@percona.com
  - name: tplavcic
    email: tomislav.plavcic@percona.com
  - name: spron-in
    email: sergey.pronin@percona.com
