{{- include "everest.operatorRoleBinding" (dict "namespace" (include ".everest.namespace" . )) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: everest-operator-local
  namespace: {{ include  "everest.namespace" . }}
subjects:
- kind: ServiceAccount
  name: everest-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: everest-operator
  apiGroup: rbac.authorization.k8s.io
