{{- include "everest.operatorRoleBinding" (dict "namespace" .Release.Namespace) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: everest-operator-local
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: everest-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: everest-operator
  apiGroup: rbac.authorization.k8s.io
