apiVersion: v1
appVersion: "1.5.0"
description: A Helm chart for installing Percona Server MongoDB Cluster Databases using the PSMDB Operator.
name: psmdb-db
home: https://www.percona.com/doc/kubernetes-operator-for-psmongodb/index.html
version: 0.1.1
maintainers:
  - name: cap1984
    email: ivan.pylypenko@percona.com
  - name: tplavcic
    email: tomislav.plavcic@percona.com
  - name: paulczar
    email: username.taken@gmail.com
