apiVersion: v2
appVersion: "1.16.0"
description: A Helm chart for installing Percona Server MongoDB Cluster Databases using the PSMDB Operator.
name: psmdb-db
home: https://www.percona.com/doc/kubernetes-operator-for-psmongodb/index.html
version: 1.16.0
maintainers:
  - name: tplavcic
    email: tomislav.plavcic@percona.com
  - name: nmarukovich
    email: natalia.marukovich@percona.com
