apiVersion: v2
appVersion: "1.22.0"
description: A Helm chart for installing Percona Server MongoDB Cluster Databases using the PSMDB Operator.
name: psmdb-db
home: https://www.percona.com/doc/kubernetes-operator-for-psmongodb/index.html
version: 1.22.0
maintainers:
  - name: nmarukovich
    email: natalia.marukovich@percona.com
  - name: jvpasinatto
    email: julio.pasinatto@percona.com
  - name: eleo007
    email: eleonora.zinchenko@percona.com
  - name: valmiranogueira
    email: valmira.nogueira@percona.com
  - name: bogdanjeler-ev
    email: bogdan.jeler@percona.com
