apiVersion: v2
name: pmm
description: A Helm chart for Percona Monitoring and Management (PMM)
type: application
version: 1.5.2
appVersion: "3.6.0"
home: https://github.com/percona/pmm
maintainers:
  - name: tibi
    email: tibor.korocz@percona.com
  - name: alex
    email: alexander.demidoff@percona.com
keywords:
  - PMM
  - Monitoring
icon: https://raw.githubusercontent.com/percona/pmm/v3/documentation/docs/assets/pmm-logo.png
