apiVersion: v2
name: pmm
description: A Helm chart for Percona Monitoring and Management (PMM)
type: application
version: 1.3.0
appVersion: "2.39.0"
home: https://github.com/percona/pmm
maintainers:
  - name: gen1us2k
    email: andrew.minkin@percona.com
  - name: tplavcic
    email: tomislav.plavcic@percona.com
  - name: bupychuk
    email: nurlan.moldomurov@percona.com
  - name: spron-in
    email: sergey.pronin@percona.com
keywords:
  - PMM
  - Monitoring
icon: https://www.percona.com/sites/default/files/pmm-logo.png
