apiVersion: v2
name: pmm
description: A Helm chart for Percona Monitoring and Management (PMM)
type: application
version: 1.4.15
appVersion: "3.5.0"
home: https://github.com/percona/pmm
maintainers:
  - name: tplavcic
    email: tomislav.plavcic@percona.com
  - name: bupychuk
    email: nurlan.moldomurov@percona.com
keywords:
  - PMM
  - Monitoring
icon: https://www.percona.com/sites/default/files/pmm-logo.png
