apiVersion: v2
name: pmm-ha
description: A Helm chart for Percona Monitoring and Management (PMM)
type: application
version: 1.3.23
appVersion: "2.44.0"
home: https://github.com/percona/pmm
maintainers:
  - name: tplavcic
    email: tomislav.plavcic@percona.com
  - name: bupychuk
    email: nurlan.moldomurov@percona.com
  - name: tibi
    email: tibor.korocz@percona.com
keywords:
  - PMM
  - Monitoring
icon: https://www.percona.com/sites/default/files/pmm-logo.png
dependencies:
  - name: victoria-metrics-cluster
    version: 0.18.0
    repository: file://charts/victoria-metrics-cluster
  - name: clickhouse
    version: 4.0.3
    repository: file://charts/clickhouse
  - name: haproxy
    version: 1.24.0
    repository: file://charts/haproxy
  - name: pg-db
    version: 2.5.2
    repository: file://charts/pg-db
  - name: pg-operator
    version: 2.5.0
    repository: file://charts/pg-operator
