apiVersion: v2
name: pmm-ha
description: A Helm chart for Percona Monitoring and Management (PMM)
type: application
version: 1.3.23
appVersion: "2.44.0"
home: https://github.com/percona/pmm
maintainers:
  - name: bupychuk
    email: nurlan.moldomurov@percona.com
  - name: tibi
    email: tibor.korocz@percona.com
keywords:
  - PMM
  - Monitoring
icon: https://www.percona.com/sites/default/files/pmm-logo.png
dependencies:
  - name: haproxy
    version: 1.24.0
    repository: https://haproxytech.github.io/helm-charts/
  - name: pg-db
    version: 2.8.0
    repository: https://percona.github.io/percona-helm-charts/
