apiVersion: v2
name: psmdb-operator-crds
description: A Helm chart for Percona Server for MongoDB Operator Custom Resource Definitions (CRDs).
type: application
version: 1.21.2
appVersion: "1.21.1"
home: https://docs.percona.com/percona-operator-for-mongodb/
maintainers:
  - name: nmarukovich
    email: natalia.marukovich@percona.com
  - name: jvpasinatto
    email: julio.pasinatto@percona.com
  - name: eleo007
    email: eleonora.zinchenko@percona.com

