{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "psmdb-operator.fullname" . }}
---
{{- end }}
{{- if .Values.rbac.create }}
{{- if or .Values.watchNamespace .Values.watchAllNamespaces }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-account-{{ include "psmdb-operator.fullname" . }}
  {{- if .Values.watchNamespace }}
  namespace: {{ .Values.watchNamespace }}
  {{- end }}
  labels:
{{ include "psmdb-operator.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "psmdb-operator.fullname" . }}
  {{- if or .Values.watchNamespace .Values.watchAllNamespaces }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
roleRef:
  {{- if or .Values.watchNamespace .Values.watchAllNamespaces }}
  kind: ClusterRole
  {{- else }}
  kind: Role
  {{- end }}
  name: {{ include "psmdb-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
