apiVersion: v2
appVersion: 1.10.0
description: A Helm chart for Deploying the Percona XtraDB Cluster Operator Kubernetes
name: pxc-operator
home: https://www.percona.com/doc/kubernetes-operator-for-pxc/kubernetes.html
version: 1.10.0
maintainers:
  - name: cap1984
    email: ivan.pylypenko@percona.com
  - name: tplavcic
    email: tomislav.plavcic@percona.com
icon: https://artifacthub.io/image/0b8875cd-6661-4269-9cf6-0fd92d59017b@1x
