apiVersion: v2
appVersion: 1.18.0
description: A Helm chart for deploying the Percona Operator for MySQL (based on Percona XtraDB Cluster)
name: pxc-operator
home: https://docs.percona.com/percona-operator-for-mysql/pxc/
version: 1.18.0
maintainers:
  - name: nmarukovich
    email: natalia.marukovich@percona.com
  - name: eleo007
    email: eleonora.zinchenko@percona.com
  - name: jvpasinatto
    email: julio.pasinatto@percona.com
icon: https://artifacthub.io/image/0b8875cd-6661-4269-9cf6-0fd92d59017b@1x
