apiVersion: v2
name: pmm3
description: PMM3 subchart wrapper
version: 0.0.1
dependencies:
  - name: pmm
    repository: "https://percona.github.io/percona-helm-charts"
    version: 1.4.*
maintainers:
  - name: mayankshah1607
    email: mayank.shah@percona.com
  - name: oksana-grishchenko
    email: oksana.grishchenko@percona.com
  - name: recharte
    email: diogo.recharte@percona.com
  - name: maxkondr
    email: maxim.kondratenko@percona.com
