{{- if .Release.IsInstall }}
{{- $secretName := (printf "everest-accounts") -}}
{{- $secret := (lookup "v1" "Secret" (include "everest.namespace" .) $secretName ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include  "everest.namespace" . }}
  annotations:
  {{- if not $secret }}
    insecure-password/admin: "true"
  {{- else }}
  {{- range $key, $value := $secret.metadata.annotations }}
    {{ $key }}: "{{ $value }}"
  {{- end }}
  {{- end }}
data:
  {{- if not $secret }}
  users.yaml: {{ tpl (.Files.Get "everest-admin.yaml.tpl") . | b64enc }}
  {{- else }}
  users.yaml: {{ index $secret.data "users.yaml" }}
  {{- end }}
{{- end }}
