apiVersion: v2
name: pg-operator
description: 'A Helm chart to deploy the Percona Operator for PostgreSQL'
type: application
version: 2.4.1
appVersion: 2.4.1
home: https://docs.percona.com/percona-operator-for-postgresql/2.0/
maintainers:
  - name: tplavcic
    email: tomislav.plavcic@percona.com
  - name: spron-in
    email: sergey.pronin@percona.com
  - name: nmarukovich
    email: natalia.marukovich@gmail.com
keywords:
  - PostgreSQL
  - Operator
  - Database
  - Postgres
  - SQL
  - RDBMS
