apiVersion: v2
name: pg-operator
description: 'A Helm chart to deploy the Percona Distribution for PostgreSQL Operator'
type: application
version: 1.2.0
appVersion: 1.2.0
home: https://github.com/percona/percona-postgresql-operator
maintainers:
  - name: cap1984
    email: ivan.pylypenko@percona.com
  - name: tplavcic
    email: tomislav.plavcic@percona.com
keywords:
  - PostgreSQL
  - Operator
  - Database
  - Postgres
  - SQL
  - RDBMS
