apiVersion: v2
name: pg-operator
description: 'A Helm chart to deploy the Percona Operator for PostgreSQL'
type: application
version: 1.3.1
appVersion: 1.3.0
home: https://docs.percona.com/percona-operator-for-postgresql/
maintainers:
  - name: cap1984
    email: ivan.pylypenko@percona.com
  - name: tplavcic
    email: tomislav.plavcic@percona.com
  - name: spron-in
    email: sergey.pronin@percona.com
keywords:
  - PostgreSQL
  - Operator
  - Database
  - Postgres
  - SQL
  - RDBMS
