{{- if .Values.psmdb }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: percona-server-mongodb-operator
  namespace: {{ include "db.namespace" . }}
spec:
  channel: stable-v1
  installPlanApproval: Manual
  name: percona-server-mongodb-operator
  source: everest-catalog
  sourceNamespace: {{ include "db.olmNamespace" . }}
  config:
    env:
    - name: DISABLE_TELEMETRY
      {{- if $.Values.telemetry }}
      value: "true"
      {{- else }}
      value: "false"
      {{- end }}
{{- end }}
