# -- Configuration for Helm chart hooks.
hooks:
  # -- Default image to use for the Helm chart hooks job.
  # @default -- `registry.k8s.io/kubectl`
  image: bitnamilegacy/kubectl
  # -- Configuration for the CSV cleanup job.
  csvCleanup: {}
    # -- Image to use for the CSV cleanup job.
    # If not set, uses the value of `hooks.image`.
    # image: ""

  # -- Configuration for the DB resources cleanup job.
  dbResourcesCleanup: {}
    # -- Image to use for the DB resources cleanup job.
    # If not set, uses the value of `hooks.image`.
    # image: ""

  # -- Configuration for the operators installer job.
  operatorsInstaller: {}
    # -- Image to use for the operators installer job.
    # If not set, uses the value of `hooks.image`.
    # image: ""

compatibility:
  # -- If set, enable OpenShift compatibility.
  openshift: false
# -- Namespace override. Defaults to the value of .Release.Namespace.
namespaceOverride: ""
# -- If set, enabled sending telemetry information.
telemetry: true
# -- If set, installs the Percona Server MongoDB operator.
psmdb: true
# -- If set, installs the Percona XtraDB Cluster operator.
pxc: true
# -- If set, installs the Percona Postgresql Server operator.
postgresql: true

# @ignore
olm:
  # -- Namespace where OLM is installed in the cluster.
  namespace: everest-olm
# -- If set, cleans up the DB resources on uninstall.
cleanupOnUninstall: true
