{{- if (and (not .Values.compatibility.openshift) .Values.olm.enabled) }}
{{- if eq .Values.olm.packageserver.tls.type "cert-manager"}}
{{- $tls := fromYaml (include "olm.certs" .) }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: olm-ca-issuer
  namespace: {{ include "everest.olmNamespace" . }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: olm-ca-cert
  namespace: {{ include "everest.olmNamespace" . }}
spec:
  secretName: olm-ca-cert
  duration: 87600h # 10 year
  renewBefore: 720h # 30 days
  isCA: true
  commonName: olm-ca
  issuerRef:
    name: olm-ca-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: olm-cert-issuer
  namespace: {{ include "everest.olmNamespace" . }}
spec:
  ca:
    secretName: olm-ca-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: olm-packageserver-tls
  namespace: {{ include "everest.olmNamespace" . }}
spec:
  secretName: packageserver-service-cert
  commonName: {{ $tls.commonName }}
  dnsNames: {{ toYaml $tls.altNames | nindent 4 }}
  duration: 8760h # 1 year
  issuerRef:
    name: olm-cert-issuer
    kind: Issuer
---
{{- end }}
{{- end }}
