{{- if (and (not .Values.compatibility.openshift) .Values.olm.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: packageserver-service
  namespace: {{ include "everest.olmNamespace" . }}
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: "5443"
    port: 5443
    protocol: TCP
    targetPort: 5443
  selector:
    app: packageserver
  type: ClusterIP
{{- end }}
